version: '3.9'


networks:
  desafio-docker:


services:
  db:
    container_name: db
    hostname: db
    image: mysql:8.0.31-debian
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    cap_add:
      - SYS_NICE # because mbind warning message
    volumes:
      - ./db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - desafio-docker
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]
      interval: 5s
      retries: 6


  app:
    container_name: app
    hostname: app
    build:
      context: ./src/node
    image: aleroxac/fullcycle:desafio-docker-node
    restart: on-failure
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_DATABASE=fullcycle
    ports:
      - 8080:8080
    networks:
      - desafio-docker
    depends_on:
      db:
        condition: service_healthy


  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.23.3-alpine-slim
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - desafio-docker
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "localhost/people" ]
      interval: 5s
      retries: 6
